# Generated by Django 2.2.12 on 2021-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, null=True)),
                ('category_description', models.TextField(null=True)),
            ],
        ),
    ]
